apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ml-models
  description: 
    Este repositório contém os modelos de machine learning utilizados no projeto MaisTodos, incluindo a implementação do modelo.
  tags:
    - ai
    - machine-learning
    - python
  annotations:
    github.com/project-slug: MaisTodos/ml-template-model
    argocd/app-name: maistodos-prod-ia-models
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:default/mlops
  system: ml-models
     